szam=""
szam2=""
szam3=""
szam4=""
szam5=""
szam6=""
szam7=""
szam8=""
szam9=""
szam10=""
szam=int(input("szam:"))
szam2=int(input("szam2:"))
szam3=int(input("szam3:"))
szam4=int(input("szam4:"))
szam5=int(input("szam5:"))
szam6=int(input("szam6:"))
szam7=int(input("szam7:"))
szam8=int(input("szam8:"))
szam9=int(input("szam9:"))
szam10=int(input("szam10:"))
print(szam,szam2,szam3,szam4,szam5,szam6,szam7,szam8,szam9,szam10)
print(szam+szam2+szam3+szam4+szam5+szam6+szam7+szam8+szam9+szam10/10)

szoveg="Integer eget pharetra magna. Nulla ex urna, congue ac tincidunt ut, interdum et metus. Phasellus nunc nunc, consectetur eu odio vitae, ullamcorper sagittis nisi. Ut quam tortor, tempus sit amet diam nec, auctor iaculis leo. Donec ut libero velit. Maecenas nisi magna, congue ut tortor quis, maximus maximus arcu. Mauris et commodo nibh. Fusce id est vehicula, consectetur mi et, molestie sapien."
print(szoveg.replace("a","g"))
szoveg="Integer eget pharetra magna. Nulla ex urna, congue ac tincidunt ut, interdum et metus. Phasellus nunc nunc, consectetur eu odio vitae, ullamcorper sagittis nisi. Ut quam tortor, tempus sit amet diam nec, auctor iaculis leo. Donec ut libero velit. Maecenas nisi magna, congue ut tortor quis, maximus maximus arcu. Mauris et commodo nibh. Fusce id est vehicula, consectetur mi et, molestie sapien."[::-1]
print(szoveg)
szoveg="Integer eget pharetra magna. Nulla ex urna, congue ac tincidunt ut, interdum et metus. Phasellus nunc nunc, consectetur eu odio vitae, ullamcorper sagittis nisi. Ut quam tortor, tempus sit amet diam nec, auctor iaculis leo. Donec ut libero velit. Maecenas nisi magna, congue ut tortor quis, maximus maximus arcu. Mauris et commodo nibh. Fusce id est vehicula, consectetur mi et, molestie sapien."
print(szoveg.strip(",.?!"))


szamszam=""
szambetu=""
szamszam2=""
szambetu2=""
szamszam3=""
szambetu3=""
szamszam4=""
szambetu4=""
szamszam5=""
szambetu5=""
szamszam6=""
szambetu6=""
szamszam7=""
szambetu7=""
szamszam8=""
szambetu8=""
szamszam9=""
szambetu9=""
szamszam10=""
szambetu10=""
szamszam=int(input("szam:"))
szambetu=str(input("szambetu:"))
szamszam2=int(input("szam:"))
szambetu2=str(input("szambetu:"))
szamszam3=int(input("szam:"))
szambetu3=str(input("szambetu:"))
szamszam4=int(input("szam:"))
szambetu4=str(input("szambetu:"))
szamszam5=int(input("szam:"))
szambetu5=str(input("szambeu:"))
szamszam6=int(input("szam:"))
szambetu6=str(input("szambetu:"))
szamszam7=int(input("szam:"))
szambetu7=str(input("szambetu:"))
szamszam8=int(input("szam:"))
szambetu8=str(input("szambetu:"))
szamszam9=int(input("szam:"))
szambetu9=str(input("szambeu:"))
szamszam10=int(input("szam:"))
szambetu10=str(input("szambetu:"))
print(szamszam+szambetu)
print(szamszam2+szambetu2)
print(szamszam3+szambetu3)
print(szamszam4+szambetu4)
print(szamszam5+szambetu5)
print(szamszam6+szambetu6)
print(szamszam7+szambetu7)
print(szamszam8+szambetu8)
print(szamszam9+szambetu9)
print(szamszam10+szambetu10)
